run:
  skip-dirs-use-default: false

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - paralleltest
    - wrapcheck
    - gosec
    - gochecknoglobals
    - musttag
    - revive
    - gomnd
    - wsl
    - exhaustruct
    - ireturn
    - nonamedreturns
    - varnamelen
    - stylecheck
    - nlreturn
    - forcetypeassert
    - gci
    - depguard

    # Deprecated ones:
    - structcheck
    - interfacer
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - golint
    - maligned
    - nosnakecase
    - scopelint

linters-settings:
  gocyclo:
    min-complexity: 15
  cyclop:
    max-complexity: 15
  funlen:
    lines: 100

issues:
  exclude-use-default: false

  exclude-rules:
    - path: main.go
      linters:
        - forbidigo
